local LSM = LibStub("LibSharedMedia-3.0")
LSM:Register("sound", "TT: (Male) Taunt", [[Interface\Addons\TankTools\audio\joey\taunt.mp3]])
LSM:Register("sound", "TT: (Male) Agro", [[Interface\Addons\TankTools\audio\joey\agro.mp3]])
LSM:Register("sound", "TT: (Male) Berserk", [[Interface\Addons\TankTools\audio\joey\berserk.mp3]])
LSM:Register("sound", "TT: (Male) Convoke", [[Interface\Addons\TankTools\audio\joey\convoke.mp3]])
LSM:Register("sound", "TT: (Male) Dispell", [[Interface\Addons\TankTools\audio\joey\dispell.mp3]])
LSM:Register("sound", "TT: (Male) Healer Mana", [[Interface\Addons\TankTools\audio\joey\healer-mana.mp3]])
LSM:Register("sound", "TT: (Male) Immune", [[Interface\Addons\TankTools\audio\joey\immune.mp3]])
LSM:Register("sound", "TT: (Male) Lost Agro", [[Interface\Addons\TankTools\audio\joey\lost-agro.mp3]])
LSM:Register("sound", "TT: (Male) Knockback", [[Interface\Addons\TankTools\audio\joey\knockback.mp3]])
LSM:Register("sound", "TT: (Male) Domination", [[Interface\Addons\TankTools\audio\joey\domination.mp3]])

LSM:Register("sound", "TT: (Female) Taunt", [[Interface\Addons\TankTools\audio\kendra\taunt.mp3]])
LSM:Register("sound", "TT: (Female) Interrupt", [[Interface\Addons\TankTools\audio\kendra\interrupt.mp3]])